import type { NextPage } from 'next'
import Head from 'next/head'
import {
  BannerTop, BannerBottom, NavBar,
  Header, Footer, MainContent
} from '../components/Organisms';

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>🗳 Rule of Thumb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Header />
      <div className="max-centered">
        <BannerTop />
        <MainContent />
        <BannerBottom />
        <hr role="separator" />
        <Footer />
      </div>
    </div>
  )
}

export default Home
