import type { NextPage } from 'next'
import Head from 'next/head'
import { NavBar } from '../components/NavBar/NavBar';
import { Header } from '../components/Header/Header';

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>🗳 Rule of Thumb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Header />
    </div>
  )
}

export default Home
